# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CTestTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CTestUseLaunchers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CheckCCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/DartConfiguration.tcl.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/Internal/CheckCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/Internal/CheckFlagCommonConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.27/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/git/gnostr-xcode/ToolX/ext/secp256k1/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/git/gnostr-xcode/ToolX/ext/secp256k1/cmake/CheckStringOptionValue.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/git/gnostr-xcode/ToolX/ext/secp256k1/cmake/CheckX86_64Assembly.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/git/gnostr-xcode/ToolX/ext/secp256k1/cmake/FindValgrind.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/git/gnostr-xcode/ToolX/ext/secp256k1/cmake/TryAppendCFlags.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/git/gnostr-xcode/ToolX/ext/secp256k1/src/CMakeLists.txt))

/Volumes/git/gnostr-xcode/ToolX/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -S/Volumes/git/gnostr-xcode/ToolX -B/Volumes/git/gnostr-xcode/ToolX
